package com.akshay.biddingsystem.controller;

import java.util.ArrayList;
import java.util.List;

import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BindingResult;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.akshay.biddingsystem.dto.InputPlaceBidDto;
import com.akshay.biddingsystem.dto.OutputResponseDto;
import com.akshay.biddingsystem.dto.ValidationMessageDto;
import com.akshay.biddingsystem.exception.ValidationException;
import com.akshay.biddingsystem.service.IBiddingService;
import com.akshay.biddingsystem.util.Messages;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;

@CrossOrigin
@RestController
@RequestMapping(value="/v1")
@Tag(name = "BidController", description = "Bid Controller For Getting Auction & Placing Bid")
public class BidController {
	
	@Autowired
	Messages messages;
	
	@Autowired
	IBiddingService iBiddingService;
	
	private final Logger logger = LoggerFactory.getLogger(this.getClass());
	
	@Operation(summary = "Get Auction Details As Per Status with Pagination")
	@ApiResponses(value = {
			@ApiResponse(responseCode = "200", description = "Fetch Auction Details Success", content = {
					@Content(mediaType = "application/json", schema = @Schema(implementation = OutputResponseDto.class)) }),
			@ApiResponse(responseCode = "404", description = "Fetch Auction Details Failure", content = @Content) })
	@GetMapping(value = "/auction", produces = "application/json")
	public ResponseEntity<OutputResponseDto> fetchAutionsAsPerStatus(@RequestParam(required = false,defaultValue = "RUNNING") String sStatus,
			@RequestParam(defaultValue = "0") int nPageNo, 
            @RequestParam(defaultValue = "3") int nPageSize) throws Exception {

		logger.info("Class File : BidController, Method Name : fetchAutionsAsPerStatus");
		logger.info("Param for Method fetchAutionsAsPerStatus - Status Code : " + sStatus);
		
		return getResponseEntity(iBiddingService.fetchAutionsAsPerStatus(sStatus,nPageNo,nPageSize));
	}
	
	@Operation(summary = "Place Auction Bid For Item Code with Version"
			+ " Note* : Required Header context - Base 64 Encoded Context, Generated By Gateway After Authentication Passed To Down Steam Services")
	@ApiResponses(value = {
			@ApiResponse(responseCode = "201", description = "Bid is Accepted", content = {
					@Content(mediaType = "application/json", schema = @Schema(implementation = OutputResponseDto.class)) }),
			@ApiResponse(responseCode = "406", description = "Bid is Rejected", content = @Content),
			@ApiResponse(responseCode = "404", description = "Item Not Found", content = @Content),
			@ApiResponse(responseCode = "401", description = "Unauthorized", content = @Content),
			@ApiResponse(responseCode = "409", description = "Bid Already Exists", content = @Content),
			@ApiResponse(responseCode = "412", description = "Highest Bid Amount Changed, Please Use Latest Version", content = @Content),
			@ApiResponse(responseCode = "500", description = "Error Occured", content = @Content) })
	@PostMapping(value = "/auction/{nItemCode}/bid", produces = "application/json")
	public ResponseEntity<OutputResponseDto> placeAuctionsBid(@RequestHeader("ETag") Long nVersion,
			@PathVariable("nItemCode") Long nItemCode,
			@Valid @RequestBody InputPlaceBidDto inputPlaceBidDto,
			final BindingResult bindingResult) throws Exception {
		
		if (bindingResult.hasErrors()) {
			List<ValidationMessageDto> v = new ArrayList<>();

			for (FieldError err : bindingResult.getFieldErrors()) {
				ValidationMessageDto e = new ValidationMessageDto();
				e.setErrorMessage(err.getDefaultMessage());
				e.setField(err.getField());
				v.add(e);

			}
			throw new ValidationException("Input parameters", false,
					messages.getStastusCode("bs.validation.exception.message.id"),
					messages.get("bs.validation.exception.message"), v.get(0).getErrorMessage());
		}
		
		logger.info("Class File : BidController, Method Name : placeAuctionsBid");
		logger.info("Header for Method placeAuctionsBid : "+nVersion);
		logger.info("Param for Method placeAuctionsBid Item Code : "+ nItemCode +", Bid Amount : " + inputPlaceBidDto.getdBidAmount());

		return getResponseEntity(iBiddingService.placeAuctionsBid(nItemCode,nVersion,inputPlaceBidDto.getdBidAmount()));
	}
	
	public ResponseEntity<OutputResponseDto> getResponseEntity(OutputResponseDto outputResponseDto) {
		logger.debug("outputResponseDto :{}" + outputResponseDto);
		HttpStatus st = null;
		String sCode = "";
		String sAppCode = "-";
		try {
			sAppCode = outputResponseDto.getStatusCode().toString();
			sCode = sAppCode.split("-")[1].toString();
			st = HttpStatus.valueOf(Integer.parseInt(sCode));

		} catch (Exception e) {
			st = HttpStatus.I_AM_A_TEAPOT;
			logger.error("Incorrect Http Header set | sAppCode:" + sAppCode + " | HttpCode:" + sCode);
		}
		return new ResponseEntity<>(outputResponseDto, st);
	}
}
